CREATE TABLE book (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	isbn VARCHAR(255) NOT NULL,
	publish_date DATE NOT NULL,
	category VARCHAR(255) NOT NULL
);